base: /
basicauth_allow_beuser: true
basicauth_allow_devipmask: false
basicauth_credentials: 'gs-mitterdorf:roding'
basicauth_enabled: true
dependencies:
  - bootstrap-package/full
  - bootstrap-package/content-elements
  - typo3/seo-sitemap
  - CodingFreaks/cf-cookiemanager
  - typo3/form
  - georgringer/news
  - georgringer/news-sitemap
  - georgringer/news-twb5
  - elaphos/sitepackage
languages:
  -
    title: Deutsch
    enabled: true
    locale: de_DE
    hreflang: ''
    base: /
    websiteTitle: ''
    navigationTitle: Deutsch
    flag: de
    languageId: 0
rootPageId: 1
settings:
  redirects:
    autoUpdateSlugs: true
websiteTitle: 'Grundschule Mitterdorf'
