page:
  logo:
    file: 'EXT:sitepackage/Resources/Public/Images/logogsm.png'
    height: 104
    width: 360
    alt: 'Logo Grundschule Mitterdorf'
  theme:
    language:
      enable: false
    copyright:
      enable: false
    contact:
      enable: true
      data:
        title: 'Grundschule Mitterdorf'
        addressLine1: 'Bgm.-Bräu-Straße 5'
        addressLine2: '93426 Roding - Mitterdorf'
        phone: '+49 (9461) 9113630'
        fax: '+49 (9461) 91136318'
        www: 'https://gs-mitterdorf.de'
    footernavigation:
      enable: false
    meta:
      navigationValue: '18'
      navigationType: directory
  fluidtemplate:
    layoutRootPath: 'EXT:sitepackage/Resources/Private/Layouts/Page/'
    partialRootPath: 'EXT:sitepackage/Resources/Private/Partials/Page/'
    templateRootPath: 'EXT:sitepackage/Resources/Private/Partials/Page/'
plugin:
  bootstrap_package:
    settings:
      scss:
        primary: '#ea6821'
        secondary: '#f1b827'
        tertiary: '#32839e'
        dark: $gray-600
        font-family-sans-serif: 'Noto Sans, sans-serif'
        quaternary: '#1a475c'
