name: deploy-production
on:
  push:
    branches:
      - main
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install dependencies
        run: composer install --no-dev
      - name: Deploy
        uses: deployphp/action@v1
        with:
          dep: deploy production
          private-key: ${{ secrets.PRIVATE_KEY }}

